language: python
python:
  - "3.6"
install:
  - pip install flask
  - pip install flask-restplus
  - pip install flask-jwt-extended
  - pip install nose
script:
  - nosetests --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
