language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose
  - pip install codeclimate-test-reporter

script:
  # - py.test --cov=app/tests/v1
  - nosetests --with-coverage --cover-package=app && coverage report

after-success:
- coveralls
# - codeclimate-test-reporter
