language: python
python:
  - "3.6"
cache: pip	
install:
  # - pip install -r requirements.txt
  - pip install flask
  - pip install flask-restplus
  - pip install flask-jwt-extended
  - pip install nose
script:
  - nosetests
